# See https://reuse.software for more info on this file
version = 1

# By default all files should be GPLv3, but
[[annotations]]
path = "**"
SPDX-FileCopyrightText = "2026 Portland State Aerospace Society <aerospace@pdx.edu>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  "./lib/decoder.cc",
  "./lib/encoder.cc",
  "./lib/ieee802_15_4_variant_decoder.cc",
  "./lib/frame_decoder_impl.cc",
  "./lib/frame_decoder_impl.h",
  "./lib/metadata.cc",
  "./lib/shift_reg.cc",
  "./include/gnuradio/uniclogs/decoder.h",
  "./include/gnuradio/uniclogs/encoder.h",
  "./include/gnuradio/uniclogs/ieee802_15_4_variant_decoder.h",
  "./include/gnuradio/uniclogs/frame_decoder.h",
  "./include/gnuradio/uniclogs/metadata.h",
  "./include/gnuradio/uniclogs/shift_reg.h",
]
SPDX-FileCopyrightText = "2019-2023, Libre Space Foundation <http://libre.space>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "./include/gnuradio/uniclogs/date.h"
precedence = "aggregate"
SPDX-FileCopyrightText = [
  "2015, 2016, 2017 Howard Hinnant",
  "2015, 2016, 2017 Howard Hinnant",
  "2016 Adrian Colomitchi",
  "2017 Florian Dang",
  "2017 Paul Thompson",
  "2018, 2019 Tomasz Kamiński",
  "2019 Jiangang Zhuang",
]

[[annotations]]
path = ["./include/gnuradio/uniclogs/viterbi.h", "./lib/viterbi/**"]
precedence = "aggregate"
SPDX-License-Identifier = "Apache V2.0"
