/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frame_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7a442157abbad70f148e39828f0c0b20)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/uniclogs/frame_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <frame_decoder_pydoc.h>

void bind_frame_decoder(py::module& m)
{

    using frame_decoder = ::gr::uniclogs::frame_decoder;


    py::class_<frame_decoder,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<frame_decoder>>(m, "frame_decoder", D(frame_decoder))

        .def(py::init(&frame_decoder::make),
             py::arg("decoder_object"),
             py::arg("input_size"),
             D(frame_decoder, make))


        ;
}
